### ISSUE TITLE
How to get Supplementary Fig.1

### ISSUE THREAD

**Issue by EarnestJJ** [dshcherbo/cfDNA-FEP#2]
Dear Dr. Shcherbo
  Recently,I read your article, it is a interesting job. When i tried to reproduce the Supplementary Fig.1, I couldn't get similar results 
 according to description of article(**The original description from article：we selected 48 COAD-specific and 48 RCC-specific peaks 
 based on their normalized scores and specificity for the corresponding cancer type**).  I think my method is not appropriate or my 
 understanding is not correct. I hope you can provide this part of the code. Thank you very much.

**Comment by dshcherbo** [comment]
Dear @EarnestJJ 
Thank you for your interest. The [Supplementary Figure 1](https://static-content.springer.com/esm/art%3A10.1186%2Fs12943-021-01491-8/MediaObjects/12943_2021_1491_MOESM2_ESM.pdf) is based on the TCGA ATAC-seq data from [Corces et al 2018](https://doi.org/10.1126/science.aav1898), not on the data generated in our study. You can get the dataset [here](https://gdc.cancer.gov/about-data/publications/ATACseq-AWG) (the `rds` file under the title _Normalized ATAC-seq insertion counts within the pan-cancer peak set_) and visualize genomic regions that we studied (the ids of the peaks are listed in the [00-all_primers.bed](https://github.com/dshcherbo/cfDNA-FEP/blob/main/primer_design/00-all_primers.bed) file) as a heatmap.
I hope this helps.

**Comment by EarnestJJ** [comment]
@dshcherbo Thank you for your reply, This is very helpful to me. But I have another question which is for example if I want to find out LUAD-specific peaks, as we know the _rds File_ has a lot of peaks of LUAD,so I can pick out peaks of LUAD firstly,  then how do I screen out the LUAD-specific peaks based on normalized scores and specificity(As described in your article, I don't konw how to screen specific peaks according to these two criteria). Looking forward to your reply, Thanks a lot.

**Comment by dshcherbo** [comment]
@EarnestJJ We did not implement any automated algorithm to select the peaks. This was done manually for each cancer (with visualization and inspection in [Xena Browser](https://xenabrowser.net/) where the dataset is preloaded) after filtering out regions that were present in other cancers.
